### ISSUE TITLE
Add support for accept attribute

### ISSUE THREAD

**Issue by johnspackman** [johnspackman/UploadMgr#4]
http://stackoverflow.com/questions/181214/file-input-accept-attribute-is-it-useful

**Comment by adrelino** [comment]
I recently implemented a similar html5 upload widget also using the accept attribute. However, some customers complained because it didn't work in Microsoft Edge (meaning it did not just ignore the accept attribute, but they were unable to upload at all): http://caniuse.com/#feat=input-file-accept
